import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useRef, useState } from "react";
import { AI_ENGINES, type EngineId } from "@/lib/kindo/limits";
import {
  getStoredKeys,
  processCareerTask,
  runWithFallback,
  setStoredKey,
} from "@/lib/kindo/careerEngine";
import { snapshot as quotaSnapshot } from "@/lib/kindo/quotaTracker";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "KindoAI — Free Multi-Engine Career Suite" },
      {
        name: "description",
        content:
          "KindoAI tailors your resume, generates a natural cover email, and chats with free AI engines — all in your browser.",
      },
      { property: "og:title", content: "KindoAI — Free Multi-Engine Career Suite" },
      {
        property: "og:description",
        content:
          "Tailor your resume and generate a natural cover email with free AI engines — fully client-side.",
      },
    ],
  }),
  component: KindoApp,
});

// ---------- Minimal safe-ish Markdown renderer (no HTML execution) ----------
function escapeHtml(s: string) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
function renderMarkdown(md: string) {
  let html = escapeHtml(md);
  html = html.replace(/^### (.*)$/gm, '<h3 class="mt-4 text-base font-semibold text-white">$1</h3>');
  html = html.replace(/^## (.*)$/gm, '<h2 class="mt-5 text-lg font-semibold text-white">$1</h2>');
  html = html.replace(/^# (.*)$/gm, '<h1 class="mt-6 text-xl font-bold text-emerald-300">$1</h1>');
  html = html.replace(/\*\*([^*]+)\*\*/g, '<strong class="text-white">$1</strong>');
  html = html.replace(/\*([^*]+)\*/g, "<em>$1</em>");
  html = html.replace(/`([^`]+)`/g, '<code class="rounded bg-white/10 px-1 py-0.5 text-[12px]">$1</code>');
  html = html.replace(/^- (.*)$/gm, '<li class="ml-5 list-disc">$1</li>');
  html = html.replace(/\n{2,}/g, '</p><p class="mt-2">');
  return `<p>${html}</p>`;
}

type View = "career" | "chat";
type ChatMsg = { role: "user" | "assistant"; text: string; error?: boolean };

function KindoApp() {
  const [view, setView] = useState<View>("career");
  const [showKeys, setShowKeys] = useState(false);
  const [keysVersion, setKeysVersion] = useState(0); // re-render after saving a key
  const [quotaVersion, setQuotaVersion] = useState(0);

  // Career state
  const [resume, setResume] = useState("");
  const [job, setJob] = useState("");
  const [engine, setEngine] = useState<EngineId>("groq");
  const [output, setOutput] = useState("");
  const [status, setStatus] = useState("Idle.");
  const [statusKind, setStatusKind] = useState<"idle" | "ok" | "warn" | "err">("idle");
  const [running, setRunning] = useState(false);

  // Chat state
  const [chatEngine, setChatEngine] = useState<EngineId>("groq");
  const [chatInput, setChatInput] = useState("");
  const [chat, setChat] = useState<ChatMsg[]>([]);
  const chatLogRef = useRef<HTMLDivElement>(null);

  const keys = useMemo(() => getStoredKeys(), [keysVersion]);
  const quotas = useMemo(() => quotaSnapshot(), [quotaVersion]);
  const hasAnyKey = Object.keys(keys).length > 0;

  useEffect(() => {
    chatLogRef.current?.scrollTo({ top: chatLogRef.current.scrollHeight });
  }, [chat]);

  const statusColor =
    statusKind === "ok"
      ? "text-emerald-300"
      : statusKind === "warn"
        ? "text-amber-300"
        : statusKind === "err"
          ? "text-red-300"
          : "text-white/50";

  async function handleRunCareer() {
    if (!resume.trim() || !job.trim()) {
      setStatus("Paste both your resume and the job details first.");
      setStatusKind("warn");
      return;
    }
    if (!hasAnyKey) {
      setStatus("Add at least one API key (click 'API Keys' in the header).");
      setStatusKind("err");
      setShowKeys(true);
      return;
    }
    setOutput("");
    setRunning(true);
    setStatus(`Contacting ${AI_ENGINES[engine].name}…`);
    setStatusKind("idle");
    await processCareerTask(resume, job, engine, {
      onChunk: (c) => setOutput((prev) => prev + c),
      onEngineSwitch: (id, reason) => {
        setStatus(`Switched to ${AI_ENGINES[id].name} (${reason}).`);
        setStatusKind("warn");
      },
      onDone: (id) => {
        setStatus(`Done — generated by ${AI_ENGINES[id].name}.`);
        setStatusKind("ok");
        setRunning(false);
        setQuotaVersion((v) => v + 1);
      },
      onError: (err) => {
        setStatus(err.message);
        setStatusKind("err");
        setRunning(false);
      },
    });
  }

  async function handleSendChat() {
    const text = chatInput.trim();
    if (!text) return;
    if (!hasAnyKey) {
      setShowKeys(true);
      return;
    }
    setChatInput("");
    setChat((c) => [...c, { role: "user", text }, { role: "assistant", text: "" }]);
    const idx = chat.length + 1; // index of the assistant bubble after state update
    let buf = "";
    await runWithFallback(
      text,
      chatEngine,
      "You are KindoAI, a helpful general-purpose assistant. Keep answers clear and concise.",
      {
        onChunk: (chunk) => {
          buf += chunk;
          setChat((c) => {
            const next = c.slice();
            if (next[idx]) next[idx] = { role: "assistant", text: buf };
            return next;
          });
        },
        onDone: () => setQuotaVersion((v) => v + 1),
        onError: (err) => {
          setChat((c) => {
            const next = c.slice();
            if (next[idx]) next[idx] = { role: "assistant", text: `Error: ${err.message}`, error: true };
            return next;
          });
        },
      },
    );
  }

  return (
    <div
      className="min-h-screen text-white antialiased"
      style={{
        background:
          "radial-gradient(120% 80% at 50% -10%, #1f2937 0%, #0b1220 60%, #050810 100%)",
      }}
    >
      {/* Header */}
      <header className="sticky top-0 z-30 border-b border-white/10 bg-slate-950/70 backdrop-blur">
        <div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-3 sm:px-6 sm:py-4">
          <div className="flex items-center gap-3">
            <div className="grid h-8 w-8 place-items-center rounded-lg bg-emerald-400 font-bold text-slate-900">
              K
            </div>
            <div>
              <div className="text-base font-semibold tracking-tight">KindoAI</div>
              <div className="text-[11px] text-white/40">Free multi-engine career suite</div>
            </div>
          </div>

          <div className="flex items-center rounded-full border border-white/10 bg-white/[0.04] p-1 text-xs font-medium">
            <button
              onClick={() => setView("chat")}
              className={`rounded-full px-3 py-1.5 sm:px-4 ${view === "chat" ? "bg-white text-slate-900" : "text-white/70"}`}
            >
              AI Chat Hub
            </button>
            <button
              onClick={() => setView("career")}
              className={`rounded-full px-3 py-1.5 sm:px-4 ${view === "career" ? "bg-white text-slate-900" : "text-white/70"}`}
            >
              Career Workspace
            </button>
          </div>

          <button
            onClick={() => setShowKeys((s) => !s)}
            className="rounded-md border border-white/10 bg-white/[0.04] px-3 py-1.5 text-xs hover:bg-white/[0.08]"
          >
            API Keys{hasAnyKey ? " ✓" : ""}
          </button>
        </div>

        {showKeys && (
          <div className="border-t border-white/10 bg-slate-950/80">
            <div className="mx-auto max-w-7xl px-4 py-4 sm:px-6">
              <div className="mb-3 text-xs text-white/50">
                Keys live only in this browser's localStorage and are sent directly to each provider.
              </div>
              <div className="grid gap-2">
                {(Object.entries(AI_ENGINES) as [EngineId, (typeof AI_ENGINES)[EngineId]][]).map(
                  ([id, e]) => (
                    <KeyRow
                      key={id}
                      engineName={e.name}
                      hint={e.keyHint}
                      keyName={e.keyName}
                      saved={!!keys[e.keyName]}
                      onSave={(val) => {
                        setStoredKey(e.keyName, val);
                        setKeysVersion((v) => v + 1);
                      }}
                    />
                  ),
                )}
              </div>
            </div>
          </div>
        )}
      </header>

      <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6">
        {view === "career" ? (
          <section>
            <div className="mb-6">
              <h1 className="text-2xl font-bold tracking-tight">Career Workspace</h1>
              <p className="mt-1 text-sm text-white/50">
                Paste your resume and the job you're targeting. KindoAI streams a tailored
                resume, a warm cover email, and ATS keyword analysis straight to your screen.
              </p>
            </div>

            <div className="grid gap-6 lg:grid-cols-[1.1fr_1.4fr]">
              {/* Left */}
              <div className="space-y-4">
                <Card>
                  <Label>Your current resume</Label>
                  <textarea
                    rows={10}
                    value={resume}
                    onChange={(e) => setResume(e.target.value)}
                    placeholder="Paste your resume here as plain text or Markdown…"
                    className="w-full resize-y rounded-lg border border-white/10 bg-slate-950/60 p-3 text-sm leading-relaxed text-white placeholder:text-white/30 focus:outline-none focus:ring-1 focus:ring-emerald-400"
                  />
                </Card>

                <Card>
                  <Label>Target job details</Label>
                  <textarea
                    rows={8}
                    value={job}
                    onChange={(e) => setJob(e.target.value)}
                    placeholder="Paste the job description, role responsibilities, and any 'about us' text…"
                    className="w-full resize-y rounded-lg border border-white/10 bg-slate-950/60 p-3 text-sm leading-relaxed text-white placeholder:text-white/30 focus:outline-none focus:ring-1 focus:ring-emerald-400"
                  />
                </Card>

                <Card>
                  <Label>AI engine</Label>
                  <select
                    value={engine}
                    onChange={(e) => setEngine(e.target.value as EngineId)}
                    className="w-full rounded-lg border border-white/10 bg-slate-950/60 p-2.5 text-sm text-white focus:outline-none focus:ring-1 focus:ring-emerald-400"
                  >
                    {(Object.entries(AI_ENGINES) as [EngineId, (typeof AI_ENGINES)[EngineId]][]).map(
                      ([id, e]) => (
                        <option key={id} value={id}>
                          {e.name} — {e.model}
                        </option>
                      ),
                    )}
                  </select>
                  <button
                    onClick={handleRunCareer}
                    disabled={running}
                    className={`mt-4 w-full rounded-lg px-4 py-3 text-sm font-semibold text-slate-900 transition ${
                      running
                        ? "cursor-not-allowed bg-emerald-400/50"
                        : "bg-emerald-400 hover:bg-emerald-300"
                    }`}
                  >
                    {running ? "Streaming…" : "Generate Tailored Application"}
                  </button>
                  <div className={`mt-2 text-xs ${statusColor}`}>{status}</div>
                </Card>
              </div>

              {/* Right */}
              <div className="space-y-4">
                <div>
                  <h2 className="mb-3 text-xs font-medium uppercase tracking-wide text-white/50">
                    Engine limits & daily usage
                  </h2>
                  <div className="grid gap-3 sm:grid-cols-2">
                    {(Object.entries(AI_ENGINES) as [EngineId, (typeof AI_ENGINES)[EngineId]][]).map(
                      ([id, e]) => {
                        const q = quotas[id];
                        const bar =
                          q.pct >= 90
                            ? "bg-red-500"
                            : q.pct >= 60
                              ? "bg-amber-400"
                              : "bg-emerald-400";
                        return (
                          <div
                            key={id}
                            className="rounded-xl border border-white/10 bg-white/[0.03] p-4"
                          >
                            <div className="flex items-center justify-between">
                              <div>
                                <div className="text-sm font-semibold text-white">{e.name}</div>
                                <div className="text-[11px] text-white/50">{e.model}</div>
                              </div>
                              <span className="text-[11px] text-white/60">
                                {q.used} / {q.cap}
                              </span>
                            </div>
                            <div className="mt-3 h-1.5 w-full overflow-hidden rounded-full bg-white/10">
                              <div
                                className={`h-full transition-all ${bar}`}
                                style={{ width: `${q.pct}%` }}
                              />
                            </div>
                            <div className="mt-2 flex items-center justify-between text-[11px] text-white/40">
                              <span>{e.limit}</span>
                              <span className="truncate pl-2">{e.attachment}</span>
                            </div>
                          </div>
                        );
                      },
                    )}
                  </div>
                </div>

                <Card padded={false}>
                  <div className="flex items-center justify-between border-b border-white/10 px-4 py-3">
                    <div className="text-sm font-semibold">Streaming output</div>
                    <button
                      onClick={async () => {
                        if (output) await navigator.clipboard.writeText(output);
                      }}
                      className="rounded-md border border-white/10 bg-white/[0.04] px-3 py-1 text-xs hover:bg-white/[0.08]"
                    >
                      Copy to Clipboard
                    </button>
                  </div>
                  <div
                    className="max-h-[560px] min-h-[320px] overflow-auto px-5 py-4 text-sm leading-relaxed text-white/90"
                    dangerouslySetInnerHTML={{
                      __html: output
                        ? renderMarkdown(output)
                        : '<div class="text-sm text-white/40">Results will stream here.</div>',
                    }}
                  />
                </Card>
              </div>
            </div>
          </section>
        ) : (
          <section>
            <div className="mb-6 flex items-end justify-between gap-4">
              <div>
                <h1 className="text-2xl font-bold tracking-tight">AI Chat Hub</h1>
                <p className="mt-1 text-sm text-white/50">
                  A general-purpose chat that routes to whichever free engine you pick.
                </p>
              </div>
              <select
                value={chatEngine}
                onChange={(e) => setChatEngine(e.target.value as EngineId)}
                className="rounded-lg border border-white/10 bg-slate-950/60 p-2 text-sm"
              >
                {(Object.entries(AI_ENGINES) as [EngineId, (typeof AI_ENGINES)[EngineId]][]).map(
                  ([id, e]) => (
                    <option key={id} value={id}>
                      {e.name}
                    </option>
                  ),
                )}
              </select>
            </div>

            <div className="flex h-[70vh] flex-col rounded-2xl border border-white/10 bg-white/[0.03]">
              <div ref={chatLogRef} className="flex-1 space-y-3 overflow-auto p-4">
                {chat.length === 0 ? (
                  <div className="grid h-full place-items-center text-sm text-white/40">
                    Start a conversation…
                  </div>
                ) : (
                  chat.map((m, i) => (
                    <div
                      key={i}
                      className={
                        m.role === "user"
                          ? "ml-auto max-w-[80%] rounded-2xl rounded-br-sm bg-emerald-500/90 px-4 py-2 text-sm text-slate-900"
                          : m.error
                            ? "mr-auto max-w-[80%] rounded-2xl rounded-bl-sm bg-red-500/20 px-4 py-2 text-sm text-red-200"
                            : "mr-auto max-w-[80%] whitespace-pre-wrap rounded-2xl rounded-bl-sm bg-white/[0.06] px-4 py-2 text-sm text-white"
                      }
                    >
                      {m.text || "…"}
                    </div>
                  ))
                )}
              </div>
              <div className="border-t border-white/10 p-3">
                <div className="flex items-end gap-2">
                  <textarea
                    rows={2}
                    value={chatInput}
                    onChange={(e) => setChatInput(e.target.value)}
                    onKeyDown={(e) => {
                      if (e.key === "Enter" && !e.shiftKey) {
                        e.preventDefault();
                        handleSendChat();
                      }
                    }}
                    placeholder="Ask anything… (Enter to send, Shift+Enter for newline)"
                    className="flex-1 resize-none rounded-lg border border-white/10 bg-slate-950/60 p-3 text-sm focus:outline-none focus:ring-1 focus:ring-emerald-400"
                  />
                  <button
                    onClick={handleSendChat}
                    className="rounded-lg bg-emerald-400 px-4 py-3 text-sm font-semibold text-slate-900 hover:bg-emerald-300"
                  >
                    Send
                  </button>
                </div>
              </div>
            </div>
          </section>
        )}
      </main>

      <footer className="mx-auto max-w-7xl px-6 py-8 text-center text-[11px] text-white/30">
        KindoAI · 100% client-side · keys stored locally in your browser
      </footer>
    </div>
  );
}

function Card({ children, padded = true }: { children: React.ReactNode; padded?: boolean }) {
  return (
    <div
      className={`rounded-2xl border border-white/10 bg-white/[0.03] ${padded ? "p-4" : ""}`}
    >
      {children}
    </div>
  );
}

function Label({ children }: { children: React.ReactNode }) {
  return (
    <label className="mb-2 block text-xs font-medium uppercase tracking-wide text-white/50">
      {children}
    </label>
  );
}

function KeyRow({
  engineName,
  hint,
  keyName,
  saved,
  onSave,
}: {
  engineName: string;
  hint: string;
  keyName: string;
  saved: boolean;
  onSave: (v: string) => void;
}) {
  const [val, setVal] = useState("");
  return (
    <div className="flex flex-wrap items-center gap-3 rounded-lg border border-white/10 bg-white/[0.03] p-3">
      <div className="min-w-0 flex-1">
        <div className="text-sm font-medium text-white">{engineName}</div>
        <div className="truncate text-[11px] text-white/40">{hint}</div>
      </div>
      <input
        type="password"
        value={val}
        onChange={(e) => setVal(e.target.value)}
        placeholder={saved ? "•••••••• saved" : keyName}
        className="w-56 rounded-md border border-white/10 bg-slate-950/60 px-2 py-1.5 text-xs text-white placeholder:text-white/30 focus:outline-none focus:ring-1 focus:ring-emerald-400"
      />
      <button
        onClick={() => {
          if (val.trim()) {
            onSave(val.trim());
            setVal("");
          }
        }}
        className="rounded-md bg-emerald-500/90 px-3 py-1.5 text-xs font-medium text-slate-900 hover:bg-emerald-400"
      >
        Save
      </button>
    </div>
  );
}
